package com.hzit.ssm.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Input {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_input.id
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_input.name
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_input.pcount
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    private Integer pcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_input.dprice
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    private BigDecimal dprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_input.price
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_input.annt
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    private String annt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_input.pname
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    private String pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_input.inputtime
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    private Date inputtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_input.id
     *
     * @return the value of t_input.id
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_input.id
     *
     * @param id the value for t_input.id
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_input.name
     *
     * @return the value of t_input.name
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_input.name
     *
     * @param name the value for t_input.name
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_input.pcount
     *
     * @return the value of t_input.pcount
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public Integer getPcount() {
        return pcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_input.pcount
     *
     * @param pcount the value for t_input.pcount
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public void setPcount(Integer pcount) {
        this.pcount = pcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_input.dprice
     *
     * @return the value of t_input.dprice
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public BigDecimal getDprice() {
        return dprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_input.dprice
     *
     * @param dprice the value for t_input.dprice
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public void setDprice(BigDecimal dprice) {
        this.dprice = dprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_input.price
     *
     * @return the value of t_input.price
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_input.price
     *
     * @param price the value for t_input.price
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_input.annt
     *
     * @return the value of t_input.annt
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public String getAnnt() {
        return annt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_input.annt
     *
     * @param annt the value for t_input.annt
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public void setAnnt(String annt) {
        this.annt = annt == null ? null : annt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_input.pname
     *
     * @return the value of t_input.pname
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_input.pname
     *
     * @param pname the value for t_input.pname
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_input.inputtime
     *
     * @return the value of t_input.inputtime
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public Date getInputtime() {
        return inputtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_input.inputtime
     *
     * @param inputtime the value for t_input.inputtime
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public void setInputtime(Date inputtime) {
        this.inputtime = inputtime;
    }
}