package com.hzit.ssm.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Output {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_output.oid
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    private Integer oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_output.name
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_output.pcount
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    private Integer pcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_output.price
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_output.annt
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    private String annt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_output.outputtime
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    private Date outputtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_output.oid
     *
     * @return the value of t_output.oid
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_output.oid
     *
     * @param oid the value for t_output.oid
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_output.name
     *
     * @return the value of t_output.name
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_output.name
     *
     * @param name the value for t_output.name
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_output.pcount
     *
     * @return the value of t_output.pcount
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public Integer getPcount() {
        return pcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_output.pcount
     *
     * @param pcount the value for t_output.pcount
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public void setPcount(Integer pcount) {
        this.pcount = pcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_output.price
     *
     * @return the value of t_output.price
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_output.price
     *
     * @param price the value for t_output.price
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_output.annt
     *
     * @return the value of t_output.annt
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public String getAnnt() {
        return annt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_output.annt
     *
     * @param annt the value for t_output.annt
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public void setAnnt(String annt) {
        this.annt = annt == null ? null : annt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_output.outputtime
     *
     * @return the value of t_output.outputtime
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public Date getOutputtime() {
        return outputtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_output.outputtime
     *
     * @param outputtime the value for t_output.outputtime
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public void setOutputtime(Date outputtime) {
        this.outputtime = outputtime;
    }
}