package com.hzit.ssm.pojo;

import java.util.Date;

public class Products {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.id
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.name
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.bid
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    private Integer bid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.sid
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.units
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    private String units;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.count
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.wvalue
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    private Integer wvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.state
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.createtime
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.id
     *
     * @return the value of t_products.id
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.id
     *
     * @param id the value for t_products.id
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.name
     *
     * @return the value of t_products.name
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.name
     *
     * @param name the value for t_products.name
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.bid
     *
     * @return the value of t_products.bid
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.bid
     *
     * @param bid the value for t_products.bid
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.sid
     *
     * @return the value of t_products.sid
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.sid
     *
     * @param sid the value for t_products.sid
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.units
     *
     * @return the value of t_products.units
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public String getUnits() {
        return units;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.units
     *
     * @param units the value for t_products.units
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public void setUnits(String units) {
        this.units = units == null ? null : units.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.count
     *
     * @return the value of t_products.count
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.count
     *
     * @param count the value for t_products.count
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.wvalue
     *
     * @return the value of t_products.wvalue
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public Integer getWvalue() {
        return wvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.wvalue
     *
     * @param wvalue the value for t_products.wvalue
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public void setWvalue(Integer wvalue) {
        this.wvalue = wvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.state
     *
     * @return the value of t_products.state
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.state
     *
     * @param state the value for t_products.state
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.createtime
     *
     * @return the value of t_products.createtime
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.createtime
     *
     * @param createtime the value for t_products.createtime
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}