package com.hzit.ssm.pojo;

public class Smalltype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_smalltype.id
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_smalltype.name
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_smalltype.bid
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    private Integer bid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_smalltype.state
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_smalltype.id
     *
     * @return the value of t_smalltype.id
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_smalltype.id
     *
     * @param id the value for t_smalltype.id
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_smalltype.name
     *
     * @return the value of t_smalltype.name
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_smalltype.name
     *
     * @param name the value for t_smalltype.name
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_smalltype.bid
     *
     * @return the value of t_smalltype.bid
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_smalltype.bid
     *
     * @param bid the value for t_smalltype.bid
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_smalltype.state
     *
     * @return the value of t_smalltype.state
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_smalltype.state
     *
     * @param state the value for t_smalltype.state
     *
     * @mbggenerated Sun Jun 02 11:18:15 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }
}